In [2]:
import numpy as np

1.

In [4]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2.

In [28]:
m = np.zeros((3,3))
print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3.

In [6]:
m = np.random.randint(1,10,(5,5))
print(m)

[[3 3 7 4 3]
 [5 9 8 6 2]
 [3 3 2 7 1]
 [5 6 4 5 9]
 [5 1 9 3 7]]


4.

In [8]:
m = np.random.random((4,4))
print(m)

[[0.03510073 0.2585926  0.08998983 0.16860556]
 [0.518321   0.16497047 0.99914482 0.48850439]
 [0.82952356 0.05177609 0.23674582 0.67527721]
 [0.35508886 0.0204347  0.69179039 0.7773458 ]]


5.

In [27]:
a = np.random.randint(1,10,5)
b = np.random.randint(1,10,5)
print(a + b)
print(a - b)
print(a * b)

[ 9 11 15 12 10]
[-7 -3 -3  2  0]
[ 8 28 54 35 25]


6.

In [31]:
a = np.random.random(7)
b = np.random.random(7)
print(np.dot(a,b))

1.2585986338543487


7.

In [32]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,3))
print(np.dot(a,b))

[[ 48  18  72]
 [ 56  32 106]]


8.

In [36]:
a = np.random.randint(1,10,(3,3))
print(np.linalg.inv(a))

[[-0.13043478  0.29813665 -0.17391304]
 [-0.08695652 -0.08695652  0.2173913 ]
 [ 0.2173913  -0.06832298 -0.04347826]]


9.

In [37]:
m = np.random.random((4,4))
print(m.T)

[[0.74572567 0.96508804 0.81374369 0.65539663]
 [0.11302973 0.61712211 0.51404175 0.26609712]
 [0.91551258 0.96899677 0.33077201 0.81345502]
 [0.12634463 0.54542999 0.69436537 0.71517476]]


10.

In [42]:
m = np.random.randint(1,10,(3,4))
v = np.random.randint(1,10,4)
print(m * v)

[[35  9 63 45]
 [56 72 27  9]
 [49  9 36 27]]


11.

In [43]:
m = np.random.random((2,3))
v = np.random.random(3)
print(m * v)

[[0.43965935 0.22055356 0.54466873]
 [0.15840089 0.31080757 0.53038529]]


12.

In [45]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
print(a * b)

[[10 18]
 [ 4 14]]


13.

In [46]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
print(np.dot(a,b))

[[42 13]
 [24  6]]


14.

In [47]:
m = np.random.randint(1,100,(5,5))
print(m.sum())

1111


15.

In [48]:
a = np.random.randint(1,10,(4,4))
b = np.random.randint(1,10,(4,4))
print(a - b)

[[ 3 -6  2  6]
 [ 7 -1 -4 -1]
 [ 1 -1 -4  3]
 [-4  0 -6  2]]


16.

In [55]:
m = np.random.random((3,3))
print(m.sum(axis=1))

[1.18759607 1.41007499 0.5590299 ]


17.

In [56]:
a = np.random.randint(0,100,(3,4))
b = np.square(a)
print(b)

[[6241 3364 7921 1444]
 [3844 2500   49  196]
 [5476 2704 5476 8649]]


18.

In [57]:
a = np.random.randint(1,50,4)
b = np.sqrt(a)
print(b)

[5.56776436 3.74165739 6.70820393 5.91607978]
